import "./globals.css";


import Navbar from "./components/Navbar";

export const metadata = {
  title: "Daedalus architecture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen w-screen relative bg-primary">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
